### ISSUE TITLE
Cloninig Process

### ISSUE THREAD

**Issue by rahul-0000-code** [SUMITRA021/WayToDestination#1]
Can you include the clone process in the readme file

**Comment by SUMITRA021** [comment]
Hello @rahul-0000-code

In this project, cloning won't work as it is specific to the NMIT campus and the floor plan is a must for the project.
One can take the idea and do it by themselves according to their requirements.

Thanks!

**Comment by rahul-0000-code** [comment]
> Hello @rahul-0000-code
> 
> In this project, cloning won't work as it is specific to the NMIT campus and the floor plan is a must for the project.
> One can take the idea and do it by themselves according to their requirements.
> 
> Thanks!

What can be the process then, could that be include here
